=== ome/ome-server/src/xml/schemas/AnalysisChain.xsd
<?xml version = "1.0" encoding = "UTF-8"?>
<!--
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
# Copyright (C) 2003 Open Microscopy Environment
#       Massachusetts Institue of Technology,
#       National Institutes of Health,
#       University of Dundee
#
#
#
#    This library is free software; you can redistribute it and/or
#    modify it under the terms of the GNU Lesser General Public
#    License as published by the Free Software Foundation; either
#    version 2.1 of the License, or (at your option) any later version.
#
#    This library is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#    Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public
#    License along with this library; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-->




<!--
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Written by:  
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-->



<!--Generated by Turbo XML 2.3.1.100. Conforms to w3c http://www.w3.org/2001/XMLSchema-->
<xsd:schema xmlns:xsd = "http://www.w3.org/2001/XMLSchema"
	 elementFormDefault = "qualified">
	<xsd:element name = "AnalysisChain">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "Nodes"/>
				<xsd:element ref = "Links"/>
			</xsd:sequence>
			<xsd:attribute name = "Name" use = "required" type = "xsd:string"/>
			<xsd:attribute name = "Locked" default = "false" type = "xsd:boolean"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "Nodes">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "Node" minOccurs = "0" maxOccurs = "unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "Node">
		<xsd:complexType>
			<xsd:sequence/>
			<xsd:attribute name = "NodeID" use = "required" type = "xsd:string"/>
			<xsd:attribute name = "ProgramName" use = "required" type = "xsd:string"/>
			<xsd:attribute name = "IteratorTag" type = "xsd:string"/>
			<xsd:attribute name = "NewFeatureTag" type = "xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "Links">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "Link" minOccurs = "0" maxOccurs = "unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "Link">
		<xsd:complexType>
			<xsd:sequence/>
			<xsd:attribute name = "FromNodeID" use = "required" type = "xsd:string"/>
			<xsd:attribute name = "FromOutputName" use = "required" type = "xsd:string"/>
			<xsd:attribute name = "ToNodeID" use = "required" type = "xsd:string"/>
			<xsd:attribute name = "ToInputName" use = "required" type = "xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "AnalysisChains">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "AnalysisChain" minOccurs = "0" maxOccurs = "unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== ome/ome-server/src/xml/fastStatsChain.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<!--
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
# Copyright (C) 2003 Open Microscopy Environment
#       Massachusetts Institute of Technology,
#       National Institutes of Health,
#       University of Dundee
#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-->




<!--
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Written by:  
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-->



<AnalysisChains xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation = "http://www.openmicroscopy.org/XMLschemas/AnalysisModule/IR3/AnalysisChain.xsd">
	<AnalysisChain Name = "Fast Stack Stats" Locked = "false">
		<Nodes>
			<Node NodeID = "Import" ProgramName = "Importer"/>
			<Node NodeID = "PlaneSums" ProgramName = "Plane statistics and sums"/>
			<Node NodeID = "StackStats" ProgramName = "Fast Stack statistics"/>
		</Nodes>
		<Links>
			<Link FromNodeID="Import" FromOutputName="Pixels" ToNodeID="PlaneSums" ToInputName="Pixels"/>
			<Link FromNodeID="Import" FromOutputName="Pixels" ToNodeID="StackStats" ToInputName="Pixels"/>

			<Link FromNodeID="PlaneSums" FromOutputName="Minima" ToNodeID="StackStats" ToInputName="PlaneMinimum"/>
			<Link FromNodeID="PlaneSums" FromOutputName="Maxima" ToNodeID="StackStats" ToInputName="PlaneMaximum"/>
			<Link FromNodeID="PlaneSums" FromOutputName="Sum i" ToNodeID="StackStats" ToInputName="PlaneSum_i"/>
			<Link FromNodeID="PlaneSums" FromOutputName="Sum i^2" ToNodeID="StackStats" ToInputName="PlaneSum_i2"/>
			<Link FromNodeID="PlaneSums" FromOutputName="Sum log(i)" ToNodeID="StackStats" ToInputName="PlaneSum_log_i"/>
			<Link FromNodeID="PlaneSums" FromOutputName="Sum Xi" ToNodeID="StackStats" ToInputName="PlaneSum_Xi"/>
			<Link FromNodeID="PlaneSums" FromOutputName="Sum Yi" ToNodeID="StackStats" ToInputName="PlaneSum_Yi"/>
			<Link FromNodeID="PlaneSums" FromOutputName="Sum Zi" ToNodeID="StackStats" ToInputName="PlaneSum_Zi"/>
		</Links>
	</AnalysisChain>
</AnalysisChains>

=== ome/ome-server/src/xml/spotChain.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<AnalysisChains
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation=
   "http://www.openmicroscopy.org/XMLschemas/AnalysisModule/IR3/AnalysisChain.xsd">

  <AnalysisChain
     Name="Find and track spots" Locked="false">

    <Nodes>
      <Node NodeID="Importer" ProgramName="Importer"/>
      <Node NodeID="Stack" ProgramName="Stack statistics"/>
      <Node NodeID="Find" ProgramName="Find spots"/>
      <Node NodeID="Track" ProgramName="Track spots"/>
    </Nodes>

    <Links>
      <Link FromNodeID="Importer" FromOutputName="Pixels"
            ToNodeID="Stack" ToInputName="Pixels"/>

      <Link FromNodeID="Importer" FromOutputName="Pixels"
            ToNodeID="Find" ToInputName="Pixels"/>

      <Link FromNodeID="Importer" FromOutputName="Dimensions"
            ToNodeID="Track" ToInputName="Dimensions"/>

      <Link FromNodeID="Stack" FromOutputName="Minima"
            ToNodeID="Find" ToInputName="Stack minima"/>
      <Link FromNodeID="Stack" FromOutputName="Maxima"
            ToNodeID="Find" ToInputName="Stack maxima"/>
      <Link FromNodeID="Stack" FromOutputName="Mean"
            ToNodeID="Find" ToInputName="Stack means"/>
      <Link FromNodeID="Stack" FromOutputName="Geomean"
            ToNodeID="Find" ToInputName="Stack geomeans"/>
      <Link FromNodeID="Stack" FromOutputName="Sigma"
            ToNodeID="Find" ToInputName="Stack sigmas"/>

      <Link FromNodeID="Find" FromOutputName="Location"
            ToNodeID="Track" ToInputName="Location"/>
      <Link FromNodeID="Find" FromOutputName="Timepoint"
            ToNodeID="Track" ToInputName="Timepoint"/>
    </Links>
  </AnalysisChain>

</AnalysisChains>

=== ome/ome-server/src/xml/OME/Tests/echoChain.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<!--
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
# Copyright (C) 2003 Open Microscopy Environment
#       Massachusetts Institue of Technology,
#       National Institutes of Health,
#       University of Dundee
#
#
#
#    This library is free software; you can redistribute it and/or
#    modify it under the terms of the GNU Lesser General Public
#    License as published by the Free Software Foundation; either
#    version 2.1 of the License, or (at your option) any later version.
#
#    This library is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#    Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public
#    License along with this library; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-->




<!--
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Written by:  Douglas Creager <dcreager@alum.mit.edu>
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-->



<AnalysisChains xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation = "http://openmicroscopy.org/XMLschemas/AnalysisModule/IR3/AnalysisChain.xsd">
  <AnalysisChain Name = "Echo chain">
	<Nodes>
	  <Node NodeID = "Files" ProgramName = "Original files"/>
	  <Node NodeID = "Import" ProgramName = "Image import"/>
      <Node NodeID = "Echo" ProgramName = "Echo test"/>
	</Nodes>
	<Links>
      <Link
         FromNodeID="Files" FromOutputName="Files"
         ToNodeID="Import" ToInputName="Files"/>
	  <Link
         FromNodeID="Import" FromOutputName="Pixels"
         ToNodeID="Echo" ToInputName="Pixels"/>
	</Links>
  </AnalysisChain>
</AnalysisChains>

=== ome/ome-server/src/xml/featureExampleChain.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<AnalysisChains xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation = "http://openmicroscopy.org/XMLschemas/AnalysisModule/IR3/AnalysisChain.xsd">
	<AnalysisChain Name = "Feature test chain">
		<Nodes>
			<Node NodeID = "Cells" ProgramName = "Find cells"/>
			<Node NodeID = "Mito" ProgramName = "Find mito"/>
			<Node NodeID = "Golgi" ProgramName = "Find golgi"/>
			<Node NodeID = "Ratio" ProgramName = "Find ratio"/>
		</Nodes>
		<Links>
			<Link FromNodeID = "Cells" FromOutputName = "Output bounds" ToNodeID = "Mito" ToInputName = "Input bounds"/>
			<Link FromNodeID = "Cells" FromOutputName = "Output bounds" ToNodeID = "Golgi" ToInputName = "Input bounds"/>
			<Link FromNodeID = "Mito" FromOutputName = "Output bounds" ToNodeID = "Ratio" ToInputName = "Mito bounds"/>
			<Link FromNodeID = "Golgi" FromOutputName = "Output bounds" ToNodeID = "Ratio" ToInputName = "Golgi bounds"/>
		</Links>
	</AnalysisChain>
</AnalysisChains>

=== ome/ome-server/src/xml/OME/Analysis/HaematoxylinEosinStainedNucleiiCounter.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<!--
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
# Copyright (C) 2003 Open Microscopy Environment
#       Massachusetts Institue of Technology,
#       National Institutes of Health,
#       University of Dundee
#
#
#
#    This library is free software; you can redistribute it and/or
#    modify it under the terms of the GNU Lesser General Public
#    License as published by the Free Software Foundation; either
#    version 2.1 of the License, or (at your option) any later version.
#
#    This library is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#    Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public
#    License along with this library; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-->

<!--
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Written by: 
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-->

<AnalysisChains
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation=
   "http://www.openmicroscopy.org/XMLschemas/AnalysisModule/IR3/AnalysisChain.xsd">

  <AnalysisChain
     Name="HandE Stained Nucleii Counter" Locked="false">

    <Nodes>
	  <Node NodeID = "Files" ProgramName = "Original files"/>
	  <Node NodeID = "Import" ProgramName = "Image import"/>
      <Node NodeID="HandE Colour Deconvolution"
      		ProgramName="Haematoxylin Eosin Colour Deconvolution"/>
	  <Node NodeID="StackStats"
            ProgramName="Stack statistics (image server)"/>
      <Node NodeID="Find Nucleii" ProgramName="Find spots"/>
    </Nodes>

    <Links>
      <Link FromNodeID="Files" FromOutputName="Files"
            ToNodeID="Import" ToInputName="Files"/>
	  <Link
         FromNodeID="Import" FromOutputName="Pixels"
         ToNodeID="HandE Colour Deconvolution" ToInputName="RGB Pixels"/>
	  <Link
         FromNodeID="HandE Colour Deconvolution" FromOutputName="Haematoxylin Staining"
         ToNodeID="StackStats" ToInputName="Pixels"/>
      <Link FromNodeID="Import" FromOutputName="Pixels"
            ToNodeID="Find Nucleii" ToInputName="Pixels"/>
      <Link FromNodeID="StackStats" FromOutputName="Minima"
            ToNodeID="Find Nucleii" ToInputName="Stack minima"/>
      <Link FromNodeID="StackStats" FromOutputName="Maxima"
            ToNodeID="Find Nucleii" ToInputName="Stack maxima"/>
      <Link FromNodeID="StackStats" FromOutputName="Mean"
            ToNodeID="Find Nucleii" ToInputName="Stack means"/>
      <Link FromNodeID="StackStats" FromOutputName="Geomean"
            ToNodeID="Find Nucleii" ToInputName="Stack geomeans"/>
      <Link FromNodeID="StackStats" FromOutputName="Sigma"
            ToNodeID="Find Nucleii" ToInputName="Stack sigmas"/>
	 <Link FromNodeID="StackStats" FromOutputName="Geosigma"
            ToNodeID="Find Nucleii" ToInputName="Stack geosigmas"/>
    </Links>
  </AnalysisChain>

`</AnalysisChains>

=== ome/ome-server/src/xml/OME/Analysis/Classifier/SignatureChain.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<!--
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
# Copyright (C) 2003 Open Microscopy Environment
#       Massachusetts Institute of Technology,
#       National Institutes of Health,
#       University of Dundee
#
#
#
#    This library is free software; you can redistribute it and/or
#    modify it under the terms of the GNU Lesser General Public
#    License as published by the Free Software Foundation; either
#    version 2.1 of the License, or (at your option) any later version.
#
#    This library is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#    Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public
#    License along with this library; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-->




<!--
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Written by:  Josiah Johnston <siah@nih.gov>
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-->



<AnalysisChains xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.openmicroscopy.org/XMLschemas/AnalysisModule/IR3/AnalysisChain.xsd">
	<AnalysisChain Name = "Signature Chains" Locked = "false">
		<Nodes>
	        <Node NodeID = "Files" ProgramName = "Original files"/>
	        <Node NodeID = "Import" ProgramName = "Image import"/>
			<Node NodeID = "maxIntensity" ProgramName = "Maximum Intensity Projection"/>
			<Node NodeID = "AreaStats" ProgramName = "Area Statistics"/>
			<Node NodeID = "Zernike" ProgramName = "Zernike Coefficients Order 3x2"/>
		</Nodes>
		<Links>
            <Link FromNodeID="Files" FromOutputName="Files"
                  ToNodeID="Import" ToInputName="Files"/>
			<Link FromNodeID="Import" FromOutputName="Other metadata" ToNodeID="maxIntensity" ToInputName="ChannelIndex"/>
			<Link FromNodeID="maxIntensity" FromOutputName="PixelsPlane" ToNodeID="AreaStats" ToInputName="PixelsPlane"/>
			<Link FromNodeID="maxIntensity" FromOutputName="PixelsPlane" ToNodeID="Zernike" ToInputName="PixelsPlane"/>
		</Links>
	</AnalysisChain>
	<AnalysisChain Name = "Hull Statistics" Locked = "false">
		<Nodes>
			<Node NodeID = "Import" ProgramName = "Importer"/>
			<Node NodeID = "maxIntensity" ProgramName = "Maximum Intensity Projection"/>
			<Node NodeID = "HullStat" ProgramName = "Hull Statistics"/>
		</Nodes>
		<Links>
			<Link FromNodeID="Import" FromOutputName="Other metadata" ToNodeID="maxIntensity" ToInputName="ChannelIndex"/>
			<Link FromNodeID="maxIntensity" FromOutputName="PixelsPlane" ToNodeID="HullStat" ToInputName="PixelsPlane"/>
		</Links>
	</AnalysisChain>
</AnalysisChains>

=== ome/ome-server/src/xml/ImageHistogramChain.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<!--
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
# Copyright (C) 2003 Open Microscopy Environment
#       Massachusetts Institue of Technology,
#       National Institutes of Health,
#       University of Dundee
#
#
#
#    This library is free software; you can redistribute it and/or
#    modify it under the terms of the GNU Lesser General Public
#    License as published by the Free Software Foundation; either
#    version 2.1 of the License, or (at your option) any later version.
#
#    This library is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#    Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public
#    License along with this library; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-->




<!--
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Written by:  Tom Macura <tmacura@nih.gov>
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-->



<AnalysisChains xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation = "http://www.openmicroscopy.org/XMLschemas/AnalysisModule/IR3/AnalysisChain.xsd">
	<AnalysisChain Name = "Image Histogram Chain" Locked = "false">
		<Nodes>
			<Node NodeID = "Files" ProgramName = "Original files"/>
			<Node NodeID = "Import" ProgramName = "Image import"/>
			<Node NodeID = "PlanesHist" ProgramName = "Plane Histogram (from OMEIS)"/>
			<Node NodeID = "StacksHist" ProgramName = "Stack Histogram (from OMEIS)"/>
		</Nodes>
		<Links>
			<Link FromNodeID="Files"  FromOutputName="Files"  ToNodeID="Import"     ToInputName="Files"/>
			<Link FromNodeID="Import" FromOutputName="Pixels" ToNodeID="PlanesHist" ToInputName="Pixels"/>
			<Link FromNodeID="Import" FromOutputName="Pixels" ToNodeID="StacksHist" ToInputName="Pixels"/>
		</Links>
	</AnalysisChain>
</AnalysisChains>
